[tox]
envlist = lints, tests
isolated_build = True

[testenv:lints]
deps = .[lint]
commands =
    black -S --check robojock
    blackdoc -S --check robojock
    flake8 robojock
    mypy robojock

[testenv:tests]
deps = .[test]
commands =
    py.test --cov=robojock robojock tests

[testenv:devs]
deps = .[develop]
commands =
    py.test --exitfirst robojock tests

[testenv:pudb]
deps = .[develop]
commands =
    py.test --pudb robojock tests